package com.oo.businessplan.admin.pojo.entity;

import java.io.Serializable;
import java.sql.Timestamp;

public class SendMessage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.id
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.senderId
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Integer senderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.sendType
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Byte sendType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.type
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.title
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.content
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.attachMent
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private String attachMent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.replyAble
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Byte replyAble;
    
    private Byte importance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.createTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Timestamp createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.state
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.sengTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Timestamp sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.upTimesTampNo
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Timestamp updateNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sendmessage.delflag
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private Byte delflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sendmessage
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.id
     *
     * @return the value of sendmessage.id
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.id
     *
     * @param id the value for sendmessage.id
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.senderId
     *
     * @return the value of sendmessage.senderId
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Integer getSenderId() {
        return senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.senderId
     *
     * @param senderId the value for sendmessage.senderId
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setSenderId(Integer senderId) {
        this.senderId = senderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.sendType
     *
     * @return the value of sendmessage.sendType
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Byte getSendType() {
        return sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.sendType
     *
     * @param sendType the value for sendmessage.sendType
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setSendType(Byte sendType) {
        this.sendType = sendType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.type
     *
     * @return the value of sendmessage.type
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.type
     *
     * @param type the value for sendmessage.type
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.title
     *
     * @return the value of sendmessage.title
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.title
     *
     * @param title the value for sendmessage.title
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.content
     *
     * @return the value of sendmessage.content
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.content
     *
     * @param content the value for sendmessage.content
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.attachMent
     *
     * @return the value of sendmessage.attachMent
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public String getAttachMent() {
        return attachMent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.attachMent
     *
     * @param attachMent the value for sendmessage.attachMent
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setAttachMent(String attachMent) {
        this.attachMent = attachMent == null ? null : attachMent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.replyAble
     *
     * @return the value of sendmessage.replyAble
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Byte getReplyAble() {
        return replyAble;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.replyAble
     *
     * @param replyAble the value for sendmessage.replyAble
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setReplyAble(Byte replyAble) {
        this.replyAble = replyAble;
    }
    
    

    public Byte getImportance() {
		return importance;
	}

	public void setImportance(Byte importance) {
		this.importance = importance;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.createTime
     *
     * @return the value of sendmessage.createTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Timestamp getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.createTime
     *
     * @param createTime the value for sendmessage.createTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.state
     *
     * @return the value of sendmessage.state
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.state
     *
     * @param state the value for sendmessage.state
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.sengTime
     *
     * @return the value of sendmessage.sengTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Timestamp getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.sengTime
     *
     * @param sengTime the value for sendmessage.sengTime
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setSendTime(Timestamp sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.upTimesTampNo
     *
     * @return the value of sendmessage.upTimesTampNo
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Timestamp getUpdateNo() {
        return updateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.upTimesTampNo
     *
     * @param upTimesTampNo the value for sendmessage.upTimesTampNo
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setUpdateNo(Timestamp updateNo) {
        this.updateNo = updateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sendmessage.delflag
     *
     * @return the value of sendmessage.delflag
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public Byte getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sendmessage.delflag
     *
     * @param delflag the value for sendmessage.delflag
     *
     * @mbg.generated Mon Sep 24 20:52:41 CST 2018
     */
    public void setDelflag(Byte delflag) {
        this.delflag = delflag;
    }
}